### ISSUE TITLE
Setup for Production Environment

### ISSUE THREAD

**Issue by junjielyu13** [alielmajdaoui/electron-react-boilerplate-multiple-windows#1]
Thank you for your article and project. I would like to ask how I can configure it to be used in a **production** environment (that is, after packaging the project). I saw that your previous article was not completely updated:

 https://medium.com/@alielmajdaoui/multiple-windows-in-electron-react-boilerplate-c6d763f38306

Looking forward to your reply

**Comment by alielmajdaoui** [comment]
@junjielyu13 I will try to write more on how to set it up for production.

**Comment by junjielyu13** [comment]
thank you!!!!

**Comment by genericcereal** [comment]
I could also really use this write up... been stuck for a while :( 

Thank you for all your help with this, btw!  The article was incredibly useful

**Comment by Sdqumar** [comment]
any update for production setup, am getting a white screen after building the app. Thanks

**Comment by Sdqumar** [comment]
here is webpack.config.renderer.prod.ts code that works when app is packaged 

```
entry: {
  main: [
    path.join(webpackPaths.srcRendererPath, 'index.tsx'),
  ],
  settings: [
    path.join(webpackPaths.srcSettingsRendererPath, 'index.tsx'),
  ],
},

output: {
  path: webpackPaths.distRendererPath,
  publicPath: './',
  filename: '[name].js',
  library: {
    type: 'umd',
  },
},


new HtmlWebpackPlugin({
      filename: 'main.html',
      template: path.join(webpackPaths.srcRendererPath, 'index.ejs'),
      minify: {
        collapseWhitespace: true,
        removeAttributeQuotes: true,
        removeComments: true,
      },
      isBrowser: false,
      isDevelopment: process.env.NODE_ENV !== 'production',
      chunks: ['main'],

    }),
    new HtmlWebpackPlugin({
      filename: path.join('settings.html'),
      template: path.join(webpackPaths.srcSettingsRendererPath, 'index.ejs'),
      minify: {
        collapseWhitespace: true,
        removeAttributeQuotes: true,
        removeComments: true,
      },
      isBrowser: false,
      isDevelopment: process.env.NODE_ENV !== 'production',
      chunks: ['settings'],

    }),
```

**Comment by alielmajdaoui** [comment]
@Sdqumar can you please send a merge request?

**Comment by alielmajdaoui** [comment]
Sorry about delay, been super busy.

Article updated https://medium.com/@alielmajdaoui/multiple-windows-in-electron-react-boilerplate-c6d763f38306 and pushed production setup.
